### ISSUE TITLE
-lm_stub is broken

### ISSUE THREAD

**Issue by Akabane87** [psp2sdk/libs#3]
When using the vitas math stub using -lm_stub, most of the functions (like cosf and sinf) return random results.

**Comment by xerpi** [comment]
I think that's because lm_stub uses the Hard Floating Point ABI, and we are not compiling with the hard fp enabled.

**Comment by 173210** [comment]
Use -mfloat-abi=hard and tell me whether it fixes or not.

**Comment by Akabane87** [comment]
My bad, you're right : it's working with -mfloat-abi=hard. I thought it was added by default by the psp2.spec, but apparently not.

**Comment by 173210** [comment]
The issues were fixed with commit b924dab351552c335d74e431f944accc51d25657 and d0eec73802b0c10f8784977ee78cfb392086de52
