### ISSUE TITLE
Broken sceDisplayWaitSetFrameBuf functions

### ISSUE THREAD

**Issue by Akabane87** [psp2sdk/libs#4]
SceInt32 sceDisplayWaitSetFrameBuf(void);
SceInt32 sceDisplayWaitSetFrameBufCB(void);
SceInt32 sceDisplayWaitSetFrameBufMulti(SceUInt32 vcount);
SceInt32 sceDisplayWaitSetFrameBufMultiCB(SceUInt32 vcount);

are probably broken. They return -1 and make the vita crash with an error message. Could the nids be incorrect ?

**Comment by 173210** [comment]
> They return -1

Probably it's an issue of Rejuvenate. You can't use them.
